# Generated by Django 4.1.7 on 2023-03-24 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_itempedido_remove_pedido_itens_pedido_itens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='nome',
            new_name='produto',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='nome_cliente',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
