# Generated by Django 4.1.7 on 2023-04-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_rename_data_pedido_pedido_data_remove_pedido_itens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='data',
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_cliente',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_produto',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='pedido',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='vl_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
    ]
